## Data Encoding 
1. Nominal/OHE Encoding
2. Label and Ordinal Encoding
3. Target Guided Ordinal Encoding

### Nominal/OHE Encoding

One hot encoding, also known as nominal endocing, is a technique used to present categorical data as numerical data which is more suitable for machine learning algorithms.  In this technique, each category is represented as a binary vector where each bit corrosponds to a unique category. For example, if we have a categorical variable 'Color' with three possible (red,green,blue) we can represent it one hot encoding is follows: 

1. Red:[1,0,0]
2. Green:[0,1,0]
3. Blue:[0,0,1]
4.

In [3]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [4]:
## Create a simple dataFrame

df=pd.DataFrame({
    'color':['red','blue','green','green','red','blue']
})

In [6]:
df.head()

   color
0    red
1   blue
2  green
3  green
4    red

In [7]:
## Create an instance of Onehotencoder
encoder=OneHotEncoder()

In [10]:
## Perform fit and transform 
enc=encoder.fit_transform(df[['color']]).toarray()

In [11]:
import pandas as pd

In [16]:
enc_df = pd.DataFrame(
    encoder.fit_transform(df[['color']]).toarray(),
    columns = encoder.get_feature_names_out()
)

In [18]:
enc_df

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          1.0        0.0
4         0.0          0.0        1.0
5         1.0          0.0        0.0

In [21]:
## For new data

encoder.transform([['blue']]).toarray()

C:\Users\Madhav Yadav\myenv\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[1., 0., 0.]])

In [24]:
pd.concat([df,enc_df],axis=1)

   color  color_blue  color_green  color_red
0    red         0.0          0.0        1.0
1   blue         1.0          0.0        0.0
2  green         0.0          1.0        0.0
3  green         0.0          1.0        0.0
4    red         0.0          0.0        1.0
5   blue         1.0          0.0        0.0

In [26]:
import seaborn as sns
data=sns.load_dataset('tips')

In [27]:
data.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [31]:
data[''].value_counts()

smoker
No     151
Yes     93
Name: count, dtype: int64

In [1]:
data['sex']

NameError: name 'data' is not defined