## XGBoost Classifier

In [1]:
# import requirement library 
import pandas as pd 
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings

warnings.filterwarnings('ignore')
import plotly.express as px 


%matplotlib inline

In [47]:
## Load data set 
data=pd.read_csv('Travel.csv')
data.head()

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,200000,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Single,1.0,1,2,1,0.0,Manager,20993.0
1,200001,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,200002,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Single,7.0,1,3,0,0.0,Executive,17090.0
3,200003,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
4,200004,0,NaN,Self Enquiry,1,8.0,Small Business,Male,2,3.0,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0

In [48]:
data.shape

(4888, 20)

In [49]:
data.describe()

,CustomerID,ProdTaken,Age,CityTier,DurationOfPitch,NumberOfPersonVisiting,NumberOfFollowups,PreferredPropertyStar,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,MonthlyIncome
count,4888.000000,4888.000000,4662.000000,4888.000000,4637.000000,4888.000000,4843.000000,4862.000000,4748.000000,4888.000000,4888.000000,4888.000000,4822.000000,4655.000000
mean,202443.500000,0.188216,37.622265,1.654255,15.490835,2.905074,3.708445,3.581037,3.236521,0.290917,3.078151,0.620295,1.187267,23619.853491
std,1411.188388,0.390925,9.316387,0.916583,8.519643,0.724891,1.002509,0.798009,1.849019,0.454232,1.365792,0.485363,0.857861,5380.698361
min,200000.000000,0.000000,18.000000,1.000000,5.000000,1.000000,1.000000,3.000000,1.000000,0.000000,1.000000,0.000000,0.000000,1000.000000
25%,201221.750000,0.000000,31.000000,1.000000,9.000000,2.000000,3.000000,3.000000,2.000000,0.000000,2.000000,0.000000,1.000000,20346.000000
50%,202443.500000,0.000000,36.000000,1.000000,13.000000,3.000000,4.000000,3.000000,3.000000,0.000000,3.000000,1.000000,1.000000,22347.000000
75%,203665.250000,0.000000,44.000000,3.000000,20.000000,3.000000,4.000000,4.000000,4.000000,1.000000,4.000000,1.000000,2.000000,25571.000000
max,204887.000000,1.000000,61.000000,3.000000,127.000000,5.000000,6.000000,5.000000,22.000000,1.000000,5.000000,1.000000,3.000000,98678.000000

In [50]:
## Checking the data types

data.dtypes

CustomerID                    int64
ProdTaken                     int64
Age                         float64
TypeofContact                object
CityTier                      int64
DurationOfPitch             float64
Occupation                   object
Gender                       object
NumberOfPersonVisiting        int64
NumberOfFollowups           float64
ProductPitched               object
PreferredPropertyStar       float64
MaritalStatus                object
NumberOfTrips               float64
Passport                      int64
PitchSatisfactionScore        int64
OwnCar                        int64
NumberOfChildrenVisiting    float64
Designation                  object
MonthlyIncome               float64
dtype: object

In [51]:
## checking the null value in pyresent in my dataset 
data.isnull().sum()

CustomerID                    0
ProdTaken                     0
Age                         226
TypeofContact                25
CityTier                      0
DurationOfPitch             251
Occupation                    0
Gender                        0
NumberOfPersonVisiting        0
NumberOfFollowups            45
ProductPitched                0
PreferredPropertyStar        26
MaritalStatus                 0
NumberOfTrips               140
Passport                      0
PitchSatisfactionScore        0
OwnCar                        0
NumberOfChildrenVisiting     66
Designation                   0
MonthlyIncome               233
dtype: int64

In [52]:
## FIrest remove the unnessarary columns 
data.drop('CustomerID',axis=1,inplace=True)

In [53]:
cat_null=[]
num_null=[]
obj=[]
for i in data.columns:
    if data[i].dtypes=='object' and data[i].isnull().sum() != 0:
        cat_null.append(i)
    elif data[i].dtypes != 'object' and data[i].isnull().sum() !=0:
        num_null.append(i)

In [54]:
cat_null

['TypeofContact']

In [55]:
num_null

['Age',
 'DurationOfPitch',
 'NumberOfFollowups',
 'PreferredPropertyStar',
 'NumberOfTrips',
 'NumberOfChildrenVisiting',
 'MonthlyIncome']

In [56]:
# for i in num_null:
#     data[i]=data[i].fillna(data[i].mean())

# for j in cat_null:
#     data[j]=data[j].fillna(data[j].mode()[0])

data.Age.fillna(data.Age.median(),inplace=True)

data.DurationOfPitch.fillna(data.DurationOfPitch.median(),inplace=True)
data.TypeofContact.fillna(data.TypeofContact.mode()[0],inplace=True)
data.NumberOfFollowups.fillna(data.NumberOfFollowups.mode()[0],inplace=True)
data.PreferredPropertyStar.fillna(data.PreferredPropertyStar.mode()[0],inplace=True)
data.NumberOfTrips.fillna(data.NumberOfTrips.median(),inplace=True)
data.NumberOfChildrenVisiting.fillna(data.NumberOfChildrenVisiting.mode()[0],inplace=True)
data.MonthlyIncome.fillna(data.MonthlyIncome.median(),inplace=True)

In [57]:
data.isnull().sum()

ProdTaken                   0
Age                         0
TypeofContact               0
CityTier                    0
DurationOfPitch             0
Occupation                  0
Gender                      0
NumberOfPersonVisiting      0
NumberOfFollowups           0
ProductPitched              0
PreferredPropertyStar       0
MaritalStatus               0
NumberOfTrips               0
Passport                    0
PitchSatisfactionScore      0
OwnCar                      0
NumberOfChildrenVisiting    0
Designation                 0
MonthlyIncome               0
dtype: int64

In [58]:
## Features Engineering 
## Create new column for feature
data['TotalVisiting']=data['NumberOfPersonVisiting'] + data['NumberOfChildrenVisiting']
data.drop(columns=['NumberOfPersonVisiting','NumberOfChildrenVisiting'])

data.head()

,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome,TotalVisiting
0,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Single,1.0,1,2,1,0.0,Manager,20993.0,3.0
1,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0,5.0
2,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Single,7.0,1,3,0,0.0,Executive,17090.0,3.0
3,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0,3.0
4,0,36.0,Self Enquiry,1,8.0,Small Business,Male,2,3.0,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0,2.0

In [59]:
data['Gender'].value_counts()

Gender
Male       2916
Female     1817
Fe Male     155
Name: count, dtype: int64

In [60]:
data['Gender']=data['Gender'].replace('Fe Male','Female')

In [61]:
data['Gender'].value_counts()

Gender
Male      2916
Female    1972
Name: count, dtype: int64

In [62]:
data.isnull().sum()

ProdTaken                   0
Age                         0
TypeofContact               0
CityTier                    0
DurationOfPitch             0
Occupation                  0
Gender                      0
NumberOfPersonVisiting      0
NumberOfFollowups           0
ProductPitched              0
PreferredPropertyStar       0
MaritalStatus               0
NumberOfTrips               0
Passport                    0
PitchSatisfactionScore      0
OwnCar                      0
NumberOfChildrenVisiting    0
Designation                 0
MonthlyIncome               0
TotalVisiting               0
dtype: int64

In [63]:
cate=[]
for i in data.columns:
    if data[i].dtypes =='object':
        cate.append(i)

In [64]:
from sklearn.preprocessing import LabelEncoder
l1=LabelEncoder()

In [65]:
for i in cate:
    data[i]=l1.fit_transform(data[i])

In [66]:
data.head()
data['Age']=[int(i) for i in data['Age']]

In [67]:
data.head()

,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome,TotalVisiting
0,1,41,1,3,6.0,2,0,3,3.0,1,3.0,2,1.0,1,2,1,0.0,2,20993.0,3.0
1,0,49,0,1,14.0,2,1,3,4.0,1,4.0,0,2.0,0,3,1,2.0,2,20130.0,5.0
2,1,37,1,1,8.0,0,1,3,4.0,0,3.0,2,7.0,1,3,0,0.0,1,17090.0,3.0
3,0,33,0,1,9.0,2,0,2,3.0,0,3.0,0,2.0,1,5,1,1.0,1,17909.0,3.0
4,0,36,1,1,8.0,3,1,2,3.0,0,4.0,0,1.0,0,5,1,0.0,1,18468.0,2.0

In [68]:
x=data.drop('OwnCar',axis=1)
y=data['OwnCar']

In [69]:
x.shape,y.shape

((4888, 19), (4888,))

In [70]:
## split the data in into train and test set 
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=42)

In [71]:
x_train.shape,y_train.shape

((3666, 19), (3666,))

In [72]:
x_test.shape,y_test.shape

((1222, 19), (1222,))

In [73]:
## Train the model for xgboost 
from xgboost import XGBClassifier

In [74]:
xgbr=XGBClassifier()

In [75]:
xgbr.fit(x_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, ...)

In [115]:
## prediction 
from sklearn.metrics import confusion_matrix,classification_report
y_pred_test=xgbr.predict(x_test)
y_pred_train=xgbr.predict(x_train)

cm_train=confusion_matrix(y_pred_train,y_train)
cm_test=confusion_matrix(y_pred_test,y_test)
cr_train=classification_report(y_pred_train,y_train)
cr_test=classification_report(y_pred_test,y_test)

print('='*50 , 'Training Accuracy ' , '='*50)
print(cm_train)
print(cr_train)
print('='*50 , 'Testing Accuracy ' , '='*50)
print(cm_test)
print(cr_test)

================================================== Training Accuracy  ==================================================
[[1259   41]
 [ 139 2227]]
              precision    recall  f1-score   support

           0       0.90      0.97      0.93      1300
           1       0.98      0.94      0.96      2366

    accuracy                           0.95      3666
   macro avg       0.94      0.95      0.95      3666
weighted avg       0.95      0.95      0.95      3666

================================================== Testing Accuracy  ==================================================
[[185 210]
 [273 554]]
              precision    recall  f1-score   support

           0       0.40      0.47      0.43       395
           1       0.73      0.67      0.70       827

    accuracy                           0.60      1222
   macro avg       0.56      0.57      0.57      1222
weighted avg       0.62      0.60      0.61      1222

In [78]:
## Xgboost hyperparameter 
param_grid = {
    "objective": ["multi:softprob"],
    "num_class": [2, 3, 4, 5, 6],   # 1 valid nahi hota
    "eval_metric": ["mlogloss"],

    "n_estimators": [100, 200, 300],
    "learning_rate": [0.01, 0.05, 0.1],
    "max_depth": [3, 5, 7],
    "min_child_weight": [1, 3, 5],
    "gamma": [0, 0.1, 0.2],

    "subsample": [0.6, 0.8, 1.0],
    "colsample_bytree": [0.6, 0.8, 1.0],

    "reg_alpha": [0, 0.1, 1],
    "reg_lambda": [1, 1.5, 2]
}

In [116]:
param_grid

{'objective': ['multi:softprob'],
 'num_class': [2, 3, 4, 5, 6],
 'eval_metric': ['mlogloss'],
 'n_estimators': [100, 200, 300],
 'learning_rate': [0.01, 0.05, 0.1],
 'max_depth': [3, 5, 7],
 'min_child_weight': [1, 3, 5],
 'gamma': [0, 0.1, 0.2],
 'subsample': [0.6, 0.8, 1.0],
 'colsample_bytree': [0.6, 0.8, 1.0],
 'reg_alpha': [0, 0.1, 1],
 'reg_lambda': [1, 1.5, 2]}

In [117]:
from sklearn.model_selection import RandomizedSearchCV

In [121]:
random_search = RandomizedSearchCV(
        estimator=XGBClassifier(),
        param_distributions=param_grid,
        n_iter=20,
        cv=3,
        verbose=2,
        n_jobs=1
    )

In [122]:
random_search.fit(x_train,y_train)

Fitting 3 folds for each of 20 candidates, totalling 60 fits
[CV] END colsample_bytree=0.8, eval_metric=mlogloss, gamma=0.2, learning_rate=0.01, max_depth=5, min_child_weight=5, n_estimators=300, num_class=2, objective=multi:softprob, reg_alpha=0.1, reg_lambda=2, subsample=1.0; total time=   0.9s
[CV] END colsample_bytree=0.8, eval_metric=mlogloss, gamma=0.2, learning_rate=0.01, max_depth=5, min_child_weight=5, n_estimators=300, num_class=2, objective=multi:softprob, reg_alpha=0.1, reg_lambda=2, subsample=1.0; total time=   0.9s
[CV] END colsample_bytree=0.8, eval_metric=mlogloss, gamma=0.2, learning_rate=0.01, max_depth=5, min_child_weight=5, n_estimators=300, num_class=2, objective=multi:softprob, reg_alpha=0.1, reg_lambda=2, subsample=1.0; total time=   0.9s
[CV] END colsample_bytree=0.6, eval_metric=mlogloss, gamma=0, learning_rate=0.05, max_depth=7, min_child_weight=5, n_estimators=200, num_class=6, objective=multi:softprob, reg_alpha=1, reg_lambda=2, subsample=0.6; total time=   1.2s
[CV] END colsample_bytree=0.6, eval_metric=mlogloss, gamma=0, learning_rate=0.05, max_depth=7, min_child_weight=5, n_estimators=200, num_class=6, objective=multi:softprob, reg_alpha=1, reg_lambda=2, subsample=0.6; total time=   1.2s
[CV] END colsample_bytree=0.6, eval_metric=mlogloss, gamma=0, learning_rate=0.05, max_depth=7, min_child_weight=5, n_estimators=200, num_class=6, objective=multi:softprob, reg_alpha=1, reg_lambda=2, subsample=0.6; total time=   1.2s
[CV] END colsample_bytree=1.0, eval_metric=mlogloss, gamma=0, learning_rate=0.05, max_depth=3, min_child_weight=5, n_estimators=100, num_class=5, objective=multi:softprob, reg_alpha=1, reg_lambda=1.5, subsample=0.8; total time=   0.4s
[CV] END colsample_bytree=1.0, eval_metric=mlogloss, gamma=0, learning_rate=0.05, max_depth=3, min_child_weight=5, n_estimators=100, num_class=5, objective=multi:softprob, reg_alpha=1, reg_lambda=1.5, subsample=0.8; total time=   0.3s
[CV] END colsample_bytree=1.0, eval_metric=mlogloss, gamma=0, learning_rate=0.05, max_depth=3, min_child_weight=5, n_estimators=100, num_class=5, objective=multi:softprob, reg_alpha=1, reg_lambda=1.5, subsample=0.8; total time=   0.4s
[CV] END colsample_bytree=1.0, eval_metric=mlogloss, gamma=0, learning_rate=0.05, max_depth=5, min_child_weight=3, n_estimators=200, num_class=4, objective=multi:softprob, reg_alpha=0.1, reg_lambda=2, subsample=0.6; total time=   0.9s
[CV] END colsample_bytree=1.0, eval_metric=mlogloss, gamma=0, learning_rate=0.05, max_depth=5, min_child_weight=3, n_estimators=200, num_class=4, objective=multi:softprob, reg_alpha=0.1, reg_lambda=2, subsample=0.6; total time=   1.0s
[CV] END colsample_bytree=1.0, eval_metric=mlogloss, gamma=0, learning_rate=0.05, max_depth=5, min_child_weight=3, n_estimators=200, num_class=4, objective=multi:softprob, reg_alpha=0.1, reg_lambda=2, subsample=0.6; total time=   0.9s
[CV] END colsample_bytree=0.6, eval_metric=mlogloss, gamma=0.2, learning_rate=0.01, max_depth=3, min_child_weight=5, n_estimators=200, num_class=2, objective=multi:softprob, reg_alpha=0.1, reg_lambda=2, subsample=0.6; total time=   0.4s
[CV] END colsample_bytree=0.6, eval_metric=mlogloss, gamma=0.2, learning_rate=0.01, max_depth=3, min_child_weight=5, n_estimators=200, num_class=2, objective=multi:softprob, reg_alpha=0.1, reg_lambda=2, subsample=0.6; total time=   0.4s
[CV] END colsample_bytree=0.6, eval_metric=mlogloss, gamma=0.2, learning_rate=0.01, max_depth=3, min_child_weight=5, n_estimators=200, num_class=2, objective=multi:softprob, reg_alpha=0.1, reg_lambda=2, subsample=0.6; total time=   0.4s
[CV] END colsample_bytree=0.6, eval_metric=mlogloss, gamma=0.2, learning_rate=0.1, max_depth=5, min_child_weight=3, n_estimators=300, num_class=4, objective=multi:softprob, reg_alpha=0, reg_lambda=2, subsample=1.0; total time=   0.7s
[CV] END colsample_bytree=0.6, eval_metric=mlogloss, gamma=0.2, learning_rate=0.1, max_depth=5, min_child_weight=3, n_estimators=300, num_class=4, objective=multi:softprob, reg_alpha=0, reg_lambda=2, subsample=1.0; total time=   0.8s
[CV] END colsample_bytree=0.6, eval_metric=mlogloss, gamma=0.2, learning_rate=0.1, max_depth=5, min_child_weight=3, n_estimators=300, num_class=4, objective=multi:softprob, reg_alpha=0, reg_lambda=2, subsample=1.0; total time=   0.8s
[CV] END colsample_bytree=0.8, eval_metric=mlogloss, gamma=0, learning_rate=0.1, max_depth=3, min_child_weight=3, n_estimators=200, num_class=4, objective=multi:softprob, reg_alpha=0, reg_lambda=1.5, subsample=1.0; total time=   0.6s
[CV] END colsample_bytree=0.8, eval_metric=mlogloss, gamma=0, learning_rate=0.1, max_depth=3, min_child_weight=3, n_estimators=200, num_class=4, objective=multi:softprob, reg_alpha=0, reg_lambda=1.5, subsample=1.0; total time=   0.5s
[CV] END colsample_bytree=0.8, eval_metric=mlogloss, gamma=0, learning_rate=0.1, max_depth=3, min_child_weight=3, n_estimators=200, num_class=4, objective=multi:softprob, reg_alpha=0, reg_lambda=1.5, subsample=1.0; total time=   0.5s
[CV] END colsample_bytree=0.8, eval_metric=mlogloss, gamma=0.2, learning_rate=0.1, max_depth=5, min_child_weight=5, n_estimators=100, num_class=3, objective=multi:softprob, reg_alpha=1, reg_lambda=1, subsample=0.6; total time=   0.3s
[CV] END colsample_bytree=0.8, eval_metric=mlogloss, gamma=0.2, learning_rate=0.1, max_depth=5, min_child_weight=5, n_estimators=100, num_class=3, objective=multi:softprob, reg_alpha=1, reg_lambda=1, subsample=0.6; total time=   0.3s
[CV] END colsample_bytree=0.8, eval_metric=mlogloss, gamma=0.2, learning_rate=0.1, max_depth=5, min_child_weight=5, n_estimators=100, num_class=3, objective=multi:softprob, reg_alpha=1, reg_lambda=1, subsample=0.6; total time=   0.4s
[CV] END colsample_bytree=1.0, eval_metric=mlogloss, gamma=0.2, learning_rate=0.01, max_depth=7, min_child_weight=3, n_estimators=100, num_class=5, objective=multi:softprob, reg_alpha=0.1, reg_lambda=1.5, subsample=0.6; total time=   0.6s
[CV] END colsample_bytree=1.0, eval_metric=mlogloss, gamma=0.2, learning_rate=0.01, max_depth=7, min_child_weight=3, n_estimators=100, num_class=5, objective=multi:softprob, reg_alpha=0.1, reg_lambda=1.5, subsample=0.6; total time=   0.6s
[CV] END colsample_bytree=1.0, eval_metric=mlogloss, gamma=0.2, learning_rate=0.01, max_depth=7, min_child_weight=3, n_estimators=100, num_class=5, objective=multi:softprob, reg_alpha=0.1, reg_lambda=1.5, subsample=0.6; total time=   0.6s
[CV] END colsample_bytree=1.0, eval_metric=mlogloss, gamma=0.1, learning_rate=0.1, max_depth=7, min_child_weight=3, n_estimators=200, num_class=2, objective=multi:softprob, reg_alpha=1, reg_lambda=1, subsample=1.0; total time=   0.4s
[CV] END colsample_bytree=1.0, eval_metric=mlogloss, gamma=0.1, learning_rate=0.1, max_depth=7, min_child_weight=3, n_estimators=200, num_class=2, objective=multi:softprob, reg_alpha=1, reg_lambda=1, subsample=1.0; total time=   0.4s
[CV] END colsample_bytree=1.0, eval_metric=mlogloss, gamma=0.1, learning_rate=0.1, max_depth=7, min_child_weight=3, n_estimators=200, num_class=2, objective=multi:softprob, reg_alpha=1, reg_lambda=1, subsample=1.0; total time=   0.4s
[CV] END colsample_bytree=0.6, eval_metric=mlogloss, gamma=0.1, learning_rate=0.1, max_depth=3, min_child_weight=5, n_estimators=200, num_class=6, objective=multi:softprob, reg_alpha=0.1, reg_lambda=1.5, subsample=0.8; total time=   0.8s
[CV] END colsample_bytree=0.6, eval_metric=mlogloss, gamma=0.1, learning_rate=0.1, max_depth=3, min_child_weight=5, n_estimators=200, num_class=6, objective=multi:softprob, reg_alpha=0.1, reg_lambda=1.5, subsample=0.8; total time=   0.8s
[CV] END colsample_bytree=0.6, eval_metric=mlogloss, gamma=0.1, learning_rate=0.1, max_depth=3, min_child_weight=5, n_estimators=200, num_class=6, objective=multi:softprob, reg_alpha=0.1, reg_lambda=1.5, subsample=0.8; total time=   0.8s
[CV] END colsample_bytree=1.0, eval_metric=mlogloss, gamma=0, learning_rate=0.05, max_depth=7, min_child_weight=1, n_estimators=100, num_class=5, objective=multi:softprob, reg_alpha=0, reg_lambda=1.5, subsample=0.8; total time=   0.7s
[CV] END colsample_bytree=1.0, eval_metric=mlogloss, gamma=0, learning_rate=0.05, max_depth=7, min_child_weight=1, n_estimators=100, num_class=5, objective=multi:softprob, reg_alpha=0, reg_lambda=1.5, subsample=0.8; total time=   0.6s
[CV] END colsample_bytree=1.0, eval_metric=mlogloss, gamma=0, learning_rate=0.05, max_depth=7, min_child_weight=1, n_estimators=100, num_class=5, objective=multi:softprob, reg_alpha=0, reg_lambda=1.5, subsample=0.8; total time=   0.6s
[CV] END colsample_bytree=1.0, eval_metric=mlogloss, gamma=0, learning_rate=0.01, max_depth=5, min_child_weight=5, n_estimators=300, num_class=6, objective=multi:softprob, reg_alpha=0, reg_lambda=1, subsample=1.0; total time=   1.3s
[CV] END colsample_bytree=1.0, eval_metric=mlogloss, gamma=0, learning_rate=0.01, max_depth=5, min_child_weight=5, n_estimators=300, num_class=6, objective=multi:softprob, reg_alpha=0, reg_lambda=1, subsample=1.0; total time=   1.3s
[CV] END colsample_bytree=1.0, eval_metric=mlogloss, gamma=0, learning_rate=0.01, max_depth=5, min_child_weight=5, n_estimators=300, num_class=6, objective=multi:softprob, reg_alpha=0, reg_lambda=1, subsample=1.0; total time=   1.4s
[CV] END colsample_bytree=0.6, eval_metric=mlogloss, gamma=0.1, learning_rate=0.1, max_depth=3, min_child_weight=1, n_estimators=200, num_class=2, objective=multi:softprob, reg_alpha=0.1, reg_lambda=1, subsample=0.8; total time=   0.5s
[CV] END colsample_bytree=0.6, eval_metric=mlogloss, gamma=0.1, learning_rate=0.1, max_depth=3, min_child_weight=1, n_estimators=200, num_class=2, objective=multi:softprob, reg_alpha=0.1, reg_lambda=1, subsample=0.8; total time=   0.5s
[CV] END colsample_bytree=0.6, eval_metric=mlogloss, gamma=0.1, learning_rate=0.1, max_depth=3, min_child_weight=1, n_estimators=200, num_class=2, objective=multi:softprob, reg_alpha=0.1, reg_lambda=1, subsample=0.8; total time=   0.5s
[CV] END colsample_bytree=1.0, eval_metric=mlogloss, gamma=0.2, learning_rate=0.05, max_depth=3, min_child_weight=5, n_estimators=200, num_class=2, objective=multi:softprob, reg_alpha=0, reg_lambda=1, subsample=1.0; total time=   0.4s
[CV] END colsample_bytree=1.0, eval_metric=mlogloss, gamma=0.2, learning_rate=0.05, max_depth=3, min_child_weight=5, n_estimators=200, num_class=2, objective=multi:softprob, reg_alpha=0, reg_lambda=1, subsample=1.0; total time=   0.4s
[CV] END colsample_bytree=1.0, eval_metric=mlogloss, gamma=0.2, learning_rate=0.05, max_depth=3, min_child_weight=5, n_estimators=200, num_class=2, objective=multi:softprob, reg_alpha=0, reg_lambda=1, subsample=1.0; total time=   0.4s
[CV] END colsample_bytree=1.0, eval_metric=mlogloss, gamma=0.1, learning_rate=0.01, max_depth=3, min_child_weight=3, n_estimators=200, num_class=3, objective=multi:softprob, reg_alpha=0, reg_lambda=2, subsample=0.6; total time=   0.6s
[CV] END colsample_bytree=1.0, eval_metric=mlogloss, gamma=0.1, learning_rate=0.01, max_depth=3, min_child_weight=3, n_estimators=200, num_class=3, objective=multi:softprob, reg_alpha=0, reg_lambda=2, subsample=0.6; total time=   0.6s
[CV] END colsample_bytree=1.0, eval_metric=mlogloss, gamma=0.1, learning_rate=0.01, max_depth=3, min_child_weight=3, n_estimators=200, num_class=3, objective=multi:softprob, reg_alpha=0, reg_lambda=2, subsample=0.6; total time=   0.6s
[CV] END colsample_bytree=1.0, eval_metric=mlogloss, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=3, n_estimators=200, num_class=4, objective=multi:softprob, reg_alpha=0, reg_lambda=1, subsample=1.0; total time=   0.8s
[CV] END colsample_bytree=1.0, eval_metric=mlogloss, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=3, n_estimators=200, num_class=4, objective=multi:softprob, reg_alpha=0, reg_lambda=1, subsample=1.0; total time=   0.7s
[CV] END colsample_bytree=1.0, eval_metric=mlogloss, gamma=0.1, learning_rate=0.05, max_depth=7, min_child_weight=3, n_estimators=200, num_class=4, objective=multi:softprob, reg_alpha=0, reg_lambda=1, subsample=1.0; total time=   0.7s
[CV] END colsample_bytree=1.0, eval_metric=mlogloss, gamma=0.2, learning_rate=0.01, max_depth=3, min_child_weight=5, n_estimators=200, num_class=2, objective=multi:softprob, reg_alpha=1, reg_lambda=1, subsample=1.0; total time=   0.4s
[CV] END colsample_bytree=1.0, eval_metric=mlogloss, gamma=0.2, learning_rate=0.01, max_depth=3, min_child_weight=5, n_estimators=200, num_class=2, objective=multi:softprob, reg_alpha=1, reg_lambda=1, subsample=1.0; total time=   0.4s
[CV] END colsample_bytree=1.0, eval_metric=mlogloss, gamma=0.2, learning_rate=0.01, max_depth=3, min_child_weight=5, n_estimators=200, num_class=2, objective=multi:softprob, reg_alpha=1, reg_lambda=1, subsample=1.0; total time=   0.3s
[CV] END colsample_bytree=0.8, eval_metric=mlogloss, gamma=0, learning_rate=0.1, max_depth=3, min_child_weight=3, n_estimators=300, num_class=6, objective=multi:softprob, reg_alpha=0, reg_lambda=2, subsample=0.8; total time=   1.2s
[CV] END colsample_bytree=0.8, eval_metric=mlogloss, gamma=0, learning_rate=0.1, max_depth=3, min_child_weight=3, n_estimators=300, num_class=6, objective=multi:softprob, reg_alpha=0, reg_lambda=2, subsample=0.8; total time=   2.1s
[CV] END colsample_bytree=0.8, eval_metric=mlogloss, gamma=0, learning_rate=0.1, max_depth=3, min_child_weight=3, n_estimators=300, num_class=6, objective=multi:softprob, reg_alpha=0, reg_lambda=2, subsample=0.8; total time=   1.3s
[CV] END colsample_bytree=0.6, eval_metric=mlogloss, gamma=0.1, learning_rate=0.1, max_depth=3, min_child_weight=3, n_estimators=100, num_class=4, objective=multi:softprob, reg_alpha=0.1, reg_lambda=1.5, subsample=0.6; total time=   0.3s
[CV] END colsample_bytree=0.6, eval_metric=mlogloss, gamma=0.1, learning_rate=0.1, max_depth=3, min_child_weight=3, n_estimators=100, num_class=4, objective=multi:softprob, reg_alpha=0.1, reg_lambda=1.5, subsample=0.6; total time=   0.3s
[CV] END colsample_bytree=0.6, eval_metric=mlogloss, gamma=0.1, learning_rate=0.1, max_depth=3, min_child_weight=3, n_estimators=100, num_class=4, objective=multi:softprob, reg_alpha=0.1, reg_lambda=1.5, subsample=0.6; total time=   0.3s

RandomizedSearchCV(cv=3,
                   estimator=XGBClassifier(base_score=None, booster=None,
                                           callbacks=None,
                                           colsample_bylevel=None,
                                           colsample_bynode=None,
                                           colsample_bytree=None, device=None,
                                           early_stopping_rounds=None,
                                           enable_categorical=False,
                                           eval_metric=None, feature_types=None,
                                           feature_weights=None, gamma=None,
                                           grow_policy=None,
                                           importance_type=None,
                                           interaction_constrain...
                   n_iter=20, n_jobs=1,
                   param_distributions={'colsample_bytree': [0.6, 0.8, 1.0],
                                        'eval_metric': ['mlogloss'],
                                        'gamma': [0, 0.1, 0.2],
                                        'learning_rate': [0.01, 0.05, 0.1],
                                        'max_depth': [3, 5, 7],
                                        'min_child_weight': [1, 3, 5],
                                        'n_estimators': [100, 200, 300],
                                        'num_class': [2, 3, 4, 5, 6],
                                        'objective': ['multi:softprob'],
                                        'reg_alpha': [0, 0.1, 1],
                                        'reg_lambda': [1, 1.5, 2],
                                        'subsample': [0.6, 0.8, 1.0]},
                   verbose=2)

In [88]:
random_search.best_params_

{'subsample': 1.0,
 'reg_lambda': 1.5,
 'reg_alpha': 0,
 'objective': 'multi:softprob',
 'num_class': 3,
 'n_estimators': 200,
 'min_child_weight': 1,
 'max_depth': 7,
 'learning_rate': 0.05,
 'gamma': 0,
 'eval_metric': 'mlogloss',
 'colsample_bytree': 0.6}

In [99]:
# Retrain the model 
hxgbr=XGBClassifier(subsample=1.0,
                   reg_almbda=1.5,
                   reg_alpha=0,
                   objective='multi:softprob',
                   num_class=3,
                   n_estimators=200,
                   min_child_weight=1,
                   max_depth=7,
                   learning_rate=0.05,
                   gamma=0,
                   eval_metric='mlogloss',
                   colsample_bytree=0.6)

In [103]:
hxgbr.fit(x_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.6, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='mlogloss',
              feature_types=None, feature_weights=None, gamma=0,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.05, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=7, max_leaves=None,
              min_child_weight=1, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=200, n_jobs=None, num_class=3, ...)

In [114]:
from xgboost import Booster
bst = Booster({'nthread':4})

In [112]:


x_train = xgbr.DMatrix(x_train)
y_train=xgbr.DMatrix(y_train)
x_test=xgbr.DMatrix(x_test)
y_test=xgbr.DMatrix(x_test)

AttributeError: 'XGBClassifier' object has no attribute 'DMatrix'